title: 
description: Cẩm nang cho người Việt Nam ở Đan Mạch!
theme: just-the-docs

url: https://vnidk.github.io

aux_links:
  Xem mã nguồn trang web: https://github.com/vnidk/vnidk.github.io

footer_content: "Bản quyền thuộc về các tác giả tại vnidk. Nội dung trên website được phân phối dựa trên <a href=\"https://github.com/vnidk/vnidk.github.io/blob/main/LICENSE\">giấy phép MIT.</a>"
