title: 
description: Cẩm nang cho người Việt Nam ở Đan Mạch!
theme: just-the-docs

url: https://vn-dk.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
